apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
    spec:
      containers:
        - name: seafile
          image: harbor.acc.ricksdomein.nl/library/seafile-mc:13.0-latest-ca
          lifecycle:
            postStart:
              exec:
                command: 
                - /bin/sh
                - -c
                - |   
                  # Wait for the file to exist
                  counter=0
                  while [ ! -f /shared/seafile/conf/seahub_settings.py ] && [ $counter -lt 60 ]; do
                    echo "Waiting for seahub_settings.py... ($counter/60)"
                    sleep 5
                    ((counter++))
                  done
                  
                  if [ -f /shared/seafile/conf/seahub_settings.py ]; then
                    echo "Adding seahub settings"
                    cat /seahub/seahub_settings.py >> /shared/seafile/conf/seahub_settings.py
                    echo "Config added successfully"
                  else
                    echo "ERROR: seahub_settings.py never appeared!"
                  fi

                  counter=0
                  while [ ! -f /opt/seafile/seafile-server-latest/seahub/thirdpart/certifi/cacert.pem ] && [ $counter -lt 60 ]; do
                    echo "Waiting for cacert.pem... ($counter/60)"
                    sleep 5
                    ((counter++))
                  done
                  
                  if [ -f /opt/seafile/seafile-server-latest/seahub/thirdpart/certifi/cacert.pem ]; then
                    echo "Adding cert"
                    cat /usr/local/share/ca-certificates/acc.ricksdomein.nl.crt >> /opt/seafile/seafile-server-latest/seahub/thirdpart/certifi/cacert.pem
                    echo "Cert added successfully"
                  else
                    echo "ERROR: cacert.pem never appeared!"
                  fi


                  # ./opt/seafile/seafile-server-latest/seahub.sh restart
                  
          env:
            - name: NODE_EXTRA_CA_CERTS
              value: "/usr/local/share/ca-certificates/acc.ricksdomein.nl.crt"
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret-secret
                  key: JWT_PRIVATE_KEY
            - name: SEAFILE_MYSQL_DB_HOST
              value: "mariadb"
            - name: SEAFILE_MYSQL_DB_PORT
              value: "3306"
            - name: SEAFILE_MYSQL_DB_USER
              value: "seafile"
            - name: SEAFILE_MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret-secret
                  key: SEAFILE_MYSQL_DB_PASSWORD
            - name: INIT_SEAFILE_MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret-secret
                  key: INIT_SEAFILE_MYSQL_ROOT_PASSWORD
            - name: SEAFILE_MYSQL_DB_CCNET_DB_NAME
              value: "ccnet_db"
            - name: SEAFILE_MYSQL_DB_SEAFILE_DB_NAME
              value: "seafile_db"
            - name: SEAFILE_MYSQL_DB_SEAHUB_DB_NAME
              value: "seahub_db"
            - name: TIME_ZONE
              value: "Europe/Amsterdam"
            - name: INIT_SEAFILE_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secret-secret
                  key: INIT_SEAFILE_ADMIN_EMAIL
            - name: INIT_SEAFILE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret-secret
                  key: INIT_SEAFILE_ADMIN_PASSWORD
            - name: SEAFILE_SERVER_LETSENCRYPT
              value: "false"
            - name: ENABLE_WIKI
              value: "true"
            - name: ENABLE_SEADOC
              value: "true"
            - name: SEADOC_SERVER_URL
              value: "https://seadoc.acc.ricksdomein.nl"
            - name: SEAFILE_SERVER_HOSTNAME
              value: "seafile.acc.ricksdomein.nl"
            - name: SEAFILE_SERVER_PROTOCOL
              value: "https" 
            - name: SITE_ROOT
              value: "/"
            - name: NON_ROOT
              value: "false"
            - name: SEAFILE_LOG_TO_STDOUT
              value: "false"
            - name: CACHE_PROVIDER
              value: "redis"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret-secret
                  key: REDIS_PASSWORD
            - name: MEMCACHED_HOST
              value: "memcached"
            - name: MEMCACHED_PORT
              value: "11211"
            - name: ENABLE_NOTIFICATION_SERVER
              value: "false"
            - name: INNER_NOTIFICATION_SERVER_URL
              value: "http://notification-server:8083"
            - name: NOTIFICATION_SERVER_URL
              value: "https://seafile.acc.ricksdomein.nl/notification"
            - name: ENABLE_SEAFILE_AI
              value: "false"
            # - name: SEAFILE_AI_SERVER_URL
            #   value: "http://seafile-ai:8888"
            # - name: SEAFILE_AI_SECRET_KEY
            #   value: ""
            - name: MD_FILE_COUNT_LIMIT
              value: "-100000"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: seafile-data
              mountPath: /shared
            - name: seahub-settings
              mountPath: /seahub
      volumes:
        - name: seafile-data
          persistentVolumeClaim:
            claimName: seafile-data
        - name: seahub-settings
          secret:
            secretName: seahub-settings
      restartPolicy: Always
      # to get image from protected repository
      # imagePullSecrets:
      #   - name: regcred